name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - '.gitignore'

env:
  DOCKER_IMAGE: uwhackweek/template

jobs:
  build-image-and-push:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Get CalenderVersion UTC Date
      id: calver
      run: echo "::set-output name=version::$(date +'%Y.%m.%d')"

    - name: Build and Push to DockerHub
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        IMAGE_NAME: ${{ env.DOCKER_IMAGE }}
        ADDITIONAL_TAG: ${{ steps.calver.outputs.version }}

    # can remove step when https://github.com/actions/virtual-environments/issues/3282 merged
    - name: Install podman 3.1.2 for redhat-actions/push-to-registry
      run: |
        . /etc/os-release
        echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
        curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/Release.key | sudo apt-key add -
        sudo apt-get update
        sudo apt-get -y upgrade
        sudo apt-get -y install podman

    - name: Also Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ env.DOCKER_IMAGE }}
        tags: ${{ steps.calver.outputs.version }}
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"

    - name: Report Image Size and Conda Packages
      if: always()
      run: |
        docker images
        docker run uwhackweek/template:latest conda list --export
